// project_vue/vue_spa/src/App.vue
<template>
    <div class="shell">
        <themeProvider>
            <buttonsHider />
            <nav class="navBody">
                <h1 class="title">Explore Upper Austria</h1>

                <div class="navContainer">
                    <ul class="nav-option-list">
                        <li class="nav-option"><RouterLink to="/">About</RouterLink></li>
                        <li class="nav-option"><RouterLink to="/photos">Photos</RouterLink></li>
                        <li class="nav-option"><RouterLink to="/contact">Contact</RouterLink></li>
                        <li class="nav-option"><RouterLink to="/mf1">MF1</RouterLink></li>
                        <li class="nav-option"><RouterLink to="/mf2">MF2</RouterLink></li>
                    </ul>
                </div>
            </nav>

            <div class="main-text">
                <Suspense>
                    <template #default>
                        <RouterView />
                    </template>

                    <template #fallback>
                        <div>Loading…</div>
                    </template>
                </Suspense>
            </div>
        </themeProvider>
    </div>
</template>

<script>
import { RouterLink, RouterView } from 'vue-router'
import themeProvider from '../components/themeProvider/themeProvider.vue';
import buttonsHider from '../../mf/src/components/ButtonsHider/buttonsHider.vue';

export default {
name: "App",
    components: {
        themeProvider,
        buttonsHider
    }
};
</script>

// project_react/react_spa/src/App.js
import About from './pages/About';
import Photos from './pages/Photos';
import Contact from './pages/Contact';

import React from 'react';
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom';
import { ButtonsHider } from '../../mf/src/components/ButtonsHider/ButtonsHider';

const MF1 = React.lazy(() => import("mfe/App"));
const MF2 = React.lazy(() => import("mfe/App2"));

function App() {
  return (
    <Router>
      <ButtonsHider />
      <nav className = 'navBody'>
        <h1 className = 'title'>Explore Upper Austria</h1>
        <div className='navContainer'>
          <ul className='nav-option-list'>
            <li className='nav-option'><Link to="/">About</Link></li>
            <li className='nav-option'><Link to="/photos">Photos</Link></li>
            <li className='nav-option'><Link to="/contact">Contact</Link></li>
            <li className='nav-option'><Link to="/mf1">MF1</Link></li>
            <li className='nav-option'><Link to="/mf2">MF2</Link></li>
          </ul>
        </div>
      </nav>
      <div className='main-text'>
        <React.Suspense fallback={<div>Loading…</div>}>
          <Routes>
            <Route path="/" element={<About/>}/>
            <Route path="/photos" element={<Photos/>}/>
            <Route path="/contact" element={<Contact/>}/>
            <Route path="/mf1/*" element={<MF1/>}/>
            <Route path="/mf2/*" element={<MF2/>}/>
          </Routes>
        </React.Suspense>
      </div>
    </Router>
  );
}

export default App;
