// project_vue/mf/src/components/ModalRequestForm/modalRequestForm.vue
<template>
	<modalWindow :is-open="open">
		<div class="modalOverlay">
			<div class="modalCard">
				<div class="modalHeader">
					<h2>Booking request</h2>

					<div class="modalChosenLocation">
						<p>{{ hotel?.name }}</p>
						<p>{{ hotel?.location }}</p>

						<div class="inputOverview">
							<p v-if = "form.name?.trim() || form.famName?.trim()">
								For: <em>{{form.name}} {{form.famName}}</em>
							</p>
							<p v-if = "form.email?.trim()">
								E-Mail: <em>{{form.email}}</em>
							</p>
							<p v-if = "form.nationality?.trim()">
								From: <em>{{form.nationality}}</em>
							</p>
							<p v-if = "form.arrDate?.trim() && form.depDate?.trim()">
								From: <em>{{form.arrDate}}</em><br/>
								Till: <em>{{form.depDate}}</em>
							</p>
						</div>
					</div>
				</div>

				<form class="modalForm" @submit.prevent="handleSubmit">
					<div class="field">
						<label for="name">Name</label>
						<input 
							id="name" 
							v-model="form.name" 
						/>
					</div>

					<div class="field">
						<label for="famName">Family Name</label>
						<input 
							id="famName" 
							v-model="form.famName" 
						/>
					</div>

					<div class="field">
						<label for="email">E-Mail</label>
						<input 
							type="email" 
							id="email" 
							pattern="^[^\s@]+@[^\s@]+\.[^\s@]+$" 
							v-model="form.email" 
						/>
					</div>

					<div class="field">
						<label for="nationality">Country</label>
						<input 
							id="nationality" 
							v-model="form.nationality" 
						/>
					</div>

					<div class="grid2">
						<div class="field">
							<label for="start">Arrival date</label>
							<input 
								type="date" 
								id="start" 
								:min="today"
								v-model="form.arrDate" 
							/>
						</div>
						<div class="field">
							<label for="end">Departure date</label>
							<input 
								type="date" 
								id="end"
								max="2026-12-31"
								:min="form.arrDate || today"
								v-model="form.depDate" 
							/>
						</div>
					</div>

					<div class="modalActions">
						<button 
							class="btnGhost" 
							type="button" 
							@click="emit('update:open', false)">
						Cancel
						</button>

						<button 
							class="btnPrimary" 
							type="submit">
						Send Request
						</button>
					</div>
				</form>
			</div>
		</div>
	</modalWindow>
</template>

<script setup>
import modalWindow from "../modalWindow/modalWindow.vue"

const form = defineModel(); 

const props = defineProps({
  	open: Boolean,
  	hotel: Object,
})

const emit = defineEmits(["update:open", "submitted"]);

const today = new Date().toISOString().slice(0, 10);

function handleSubmit() {
	emit("submitted", { ...form.value, hotel: props.hotel })
  	emit("update:open", false);
}
</script>

// project_react/mf/src/components/ModalRequestForm/modalRequestForm.jsx
import ModalWindow from "../modalWindow/modalWindow";
import { useState } from "react";


export default function ModalRequestForm({open, hotel, form, setForm, onClose, onSubmitted}){

    if(!open) return null;

    const today = new Date().toISOString().slice(0, 10);

    const [form, setForm] = useState({
        name: "",
        famName: "",
        nationality: "",
        arrDate: "",
        depDate: "",
        email: "",
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setForm((prev) => ({ ...prev, [name]: value }));
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        if(!e.currentTarget.reportValidity()) return;

        onSubmitted({...form, hotel});
        setForm("");
    }

    return (
        <ModalWindow isOpen={open}>
        <div className="modalOverlay">
            <div className="modalCard">
            <div className="modalHeader">
                <h2>Booking request</h2>
                <div className="modalChosenLocation">
                    <p>{hotel?.name}</p>
                    <p>{hotel?.location}</p><br/>
                    <div className="inputOverview">
                        {(form.name?.trim() || form.famName?.trim()) && (
                            <p>For: <em>{form.name} {form.famName}</em></p>
                        )}
                        {form.email?.trim() && (
                            <p>E-Mail: <em>{form.email}</em></p>
                        )}
                        {form.nationality?.trim() && (
                            <p>From: <em>{form.nationality}</em></p>
                        )}
                        {(form.arrDate?.trim() && form.depDate?.trim()) && (
                            <>
                                <p>From: <em>{form.arrDate}</em></p>
                                <p>Till: <em>{form.depDate}</em></p>
                            </>
                        )}
                    </div>
                </div>
            </div>
            

            <form className="modalForm" onSubmit={handleSubmit}>
                <div className="field">
                    <label htmlFor="name">Name</label>
                    <input 
                        id="name" 
                        name="name" 
                        value={form.name} 
                        onChange={handleChange} 
                    />
                </div>

                <div className="field">
                    <label htmlFor="famName">Family Name</label>
                    <input 
                        id="famName" 
                        name="famName" 
                        value={form.famName} 
                        onChange={handleChange} 
                    />
                </div>

                <div className="field">
                    <label htmlFor="email">E-Mail</label>
                    <input 
                        type="email" 
                        id="email" 
                        name="email" 
                        value={form.email} 
                        onChange={handleChange}
                        pattern="^[^\s@]+@[^\s@]+\.[^\s@]+$"
                        required 
                    />
                </div>

                <div className="field">
                    <label htmlFor="nationality">Country</label>
                    <input 
                        id="nationality" 
                        name="nationality" 
                        value={form.nationality} 
                        onChange={handleChange} 
                    />
                </div>

                <div className="grid2">
                <div className="field">
                    <label htmlFor="start">Arrival date</label>
                    <input
                        type="date"
                        id="start"
                        name="arrDate"
                        value={form.arrDate}
                        min={today}
                        max="2026-12-31"
                        onChange={handleChange}
                    />
                </div>

                <div className="field">
                    <label htmlFor="end">Departure date</label>
                    <input
                        type="date"
                        id="end"
                        name="depDate"
                        value={form.depDate}
                        min={form.arrDate}
                        max="2026-12-31"
                        onChange={handleChange}
                    />
                </div>
                </div>

                <div className="modalActions">
                    <button 
                        className="btnGhost" 
                        type="button" 
                        onClick={onClose}
                        >Cancel</button>
                    <button 
                        className="btnPrimary" 
                        type="submit"
                        >Send Request</button>
                </div>
            </form>
            </div>
        </div>
        </ModalWindow>
    )
}
