// project_react/react_spa/src/components/themeProvider/themeProvider.jsx
import React, { useState, useEffect } from "react";
import { ThemeContext } from "./themeContext";

export function ThemeProvider({ children }) {
  const [theme, setTheme] = useState("light"); 

  const toggleTheme = () => {
    setTheme((prev) => (prev === "light" ? "dark" : "light"));
  };

  useEffect(() => {
    document.body.classList.remove("light", "dark");
    document.body.classList.add(theme);
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      {children}
    </ThemeContext.Provider>
  );
}

// project_vue/vue_spa/components/themeProvider/themeProvider.vue
<template>
    <slot></slot>
</template>
<script>
    import { ref, provide, watchEffect } from "vue";
    import { ThemeKey } from "./themeContext";

    export default {
        setup() {
            const theme = ref("light");

            const toggleTheme = () => {
                theme.value = theme.value === "light"? "dark": "light";
            }

            watchEffect(() => {
                document.body.classList.remove("light", "dark");
                document.body.classList.add(theme.value);
            });

            provide(ThemeKey, {theme, toggleTheme});

            return{};
        },
    }
</script>
