// project_react/react_spa/src/components/themeProvider/themeSwitcher.jsx
import { useContext } from "react";
import { ThemeContext } from "./themeContext";
import './themeSwitcher.css'

export function ThemeSwitcher() {
  const { theme, toggleTheme } = useContext(ThemeContext);

  return (
    <button onClick={toggleTheme} className="themeSwitcher">
      {theme === "light" ? "🌑" : "☀️"}
    </button>
  );
}

// project_vue/vue_spa/components/themeProvider/themeSwitcher.vue
<template>
    <button @click="toggleTheme" class="themeSwitcher">
        {{ theme === "light" ? "🌑" : "☀️" }}
    </button>
</template>

<script>
import { useTheme } from './themeContext';
import "./themeSwitcher.css"

export default {
    setup() {
        const {theme, toggleTheme} = useTheme();
        return {theme, toggleTheme};
    },
}
</script>
