// project_react/mf/src/components/modalWindow/embMW.jsx
import React from "react";
import ModalWindow from "./modalWindow";
import { useState, useRef } from "react";
import './modalWindow.css'

const ModalSetter = () =>{
    let numberOfLocations = useRef(0);
    const [open, setOpen] = useState(false);
    const cities = localStorage.getItem("Hotels");
    const parsed = JSON.parse(cities);

    const handleClose = () =>{
        setOpen(false);
    };

    const handleOpen = () =>{
        setOpen(true);
    };

    return(
        <div className="container">
            <button className = "modalBtn" onClick={handleOpen}>
                Locations
            </button>
            <ModalWindow isOpen={open} onClose={handleClose}>
                {parsed.length == 0? <div>Choose your favorite locations to see the events nearby!</div>: 
                <>
                <p>Favorite locations ({numberOfLocations.current = parsed.length}): </p>
                
                <div>
                    {parsed.map((loc, i) => (
                        <div key={i}>
                            {loc}
                        </div>
                    ))}
                </div>
                </>
                } 
            </ModalWindow>
        </div>
    )
};

export default ModalSetter;

// project_vue/mf/src/components/modalWindow/embMW.vue
<template>
    <div class="container">
        <button @click="handleOpen" class="modalBtn" >
            Locations
        </button>
        <modalWindow :is-open="open" :on-close="handleClose">
            <div v-if="parsed.length == 0">
                Choose your favorite locations to see the events nearby!
            </div>

            <div v-else>
                <p>Favorite locations ({{ numberOfLocations = parsed.length }}): </p>

                <div v-for="loc in parsed">
                    {{ loc }}
                </div>
            </div>
        </modalWindow>
    </div>
</template>

<script setup>
    import modalWindow from './modalWindow.vue';
    import { ref } from 'vue';

    const open = ref(false);
    const numberOfLocations = ref(0);
    
    const cities = localStorage.getItem("Hotels");
    const parsed = JSON.parse(cities);

    const handleClose = () => {
        open.value = false;
    };

    const handleOpen = () => {
        open.value = true;
    };
</script>
